import os
from fastapi import FastAPI, Request, HTTPException
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
import uvicorn
from dotenv import load_dotenv

# 1. IMPORT YOUR ENGINE
from app.engine import PyCraftEngine

load_dotenv()

app = FastAPI(title="PyCraft-Gen")

# 2. INITIALIZE THE ENGINE (Point to your 4.36GB file)
# This loads the model into RAM once when the server starts
MODEL_PATH = "models/qwen2.5-coder-7b-instruct.Q4_K_M.gguf"
engine = PyCraftEngine(MODEL_PATH)

app.mount("/static", StaticFiles(directory="app/static"), name="static")
templates = Jinja2Templates(directory="app/templates")

class CodeRequest(BaseModel):
    prompt: str

@app.get("/")
async def read_root(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

@app.post("/generate")
async def generate_code(request: CodeRequest):
    try:
        # 3. CALL THE REAL MODEL
        user_input = request.prompt
        generated_code = engine.generate(user_input)
        
        # Simple analysis for now
        analysis = "Generated by PyCraft-Gen (Local CPU Inference)"
        
        return {"code": generated_code, "analysis": analysis}
    except Exception as e:
        print(f"Error during generation: {e}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    uvicorn.run("app.main:app", host="127.0.0.1", port=8000, reload=False)